# Generated by Django 3.2.7 on 2021-09-12 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('instagram', models.CharField(blank=True, max_length=256, null=True)),
                ('snapchat', models.CharField(blank=True, max_length=256, null=True)),
                ('others', models.TextField()),
            ],
        ),
    ]
