# Generated by Django 3.2.7 on 2021-09-12 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='others',
            field=models.TextField(blank=True, null=True),
        ),
    ]
