# Generated by Django 3.2.8 on 2021-12-11 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_product_others'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='product',
            new_name='People',
        ),
    ]
