# Generated by Django 3.2.8 on 2021-12-11 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_people_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='email',
            field=models.EmailField(default='SRM Email only**', max_length=256),
        ),
    ]
